services:
  koshibar-trojan:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: koshibar-trojan

    environment:
      PORT: "8080"

    ports:
      - "8080:8080"

    restart: unless-stopped
